### ISSUE TITLE
频道私信无法发送

### ISSUE THREAD

**Issue by JIAFALSEDREAM** [hsyhhssyy/amiyabot-hsyhhssyy-dicegirl#3]
![b683b0eaefe8f1234678768b4c74a51](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-dicegirl/assets/121747365/202ff480-6d03-4d09-ba63-38b3f93e1d72)

**Comment by hsyhhssyy** [comment]
啊频道，我其实从来不用频道，也没对频道做过兼容，我看着改一下吧，不过改了也没法测试。
